import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { canonicalJson } from "../src/document/canonicalJson.js";

/*
 * A golden test over a real document's structure.
 *
 * `test/fixtures/document.json` was produced mechanically from a real
 * application's document: every key, every nesting level and every array length
 * is the original's, and every string value was replaced with deterministic
 * nonsense of the same length. The shape is real -- seven top-level keys, arrays
 * of records, seven levels of nesting, 11kB -- and none of the content is.
 * Verified at generation time: not one of the 75 distinctive strings in the
 * original survives in the fixture.
 *
 * Why a real shape rather than an invented one: the unit tests each isolate a
 * single rule, and a hand-made fixture only ever exercises the rules its author
 * thought of. A document this size combines them at a scale nobody composes by
 * hand.
 *
 * The golden file itself was generated by the code it tests, so on its own it
 * would only lock in current behaviour. It does not stand on its own: the
 * checks below derive the expected bytes from a *different* implementation --
 * sort the document independently, then hand it to plain `JSON.stringify`.
 * Sorting is the only transformation canonicalJson performs beyond stringify,
 * so for an already-sorted input the two must agree byte for byte. That makes
 * the expectation an independent oracle rather than a snapshot of the code.
 *
 * The golden file stays as a drift detector, because post-write verification
 * compares uploaded bytes against exactly this output.
 */

const source = readFileSync(new URL("./fixtures/document.json", import.meta.url), "utf8");
const golden = readFileSync(new URL("./fixtures/document.canonical.json", import.meta.url), "utf8");

/** Order-insensitive, so it cannot be satisfied by the same sorting under test. */
function deepEqual(left: unknown, right: unknown): boolean {
  if (Array.isArray(left) || Array.isArray(right)) {
    return Array.isArray(left) && Array.isArray(right)
      && left.length === right.length
      && left.every((value, index) => deepEqual(value, right[index]));
  }
  if (left && right && typeof left === "object" && typeof right === "object") {
    const leftKeys = Object.keys(left).sort();
    const rightKeys = Object.keys(right).sort();
    return leftKeys.length === rightKeys.length
      && leftKeys.every((key, index) => key === rightKeys[index])
      && leftKeys.every((key) => deepEqual((left as Record<string, unknown>)[key], (right as Record<string, unknown>)[key]));
  }
  return Object.is(left, right);
}

function keysSortedEverywhere(value: unknown): boolean {
  if (Array.isArray(value)) return value.every(keysSortedEverywhere);
  if (value && typeof value === "object") {
    const keys = Object.keys(value);
    return keys.every((key, index) => index === 0 || keys[index - 1]! <= key)
      && keys.every((key) => keysSortedEverywhere((value as Record<string, unknown>)[key]));
  }
  return true;
}

describe("canonicalJson over a real document shape", () => {
  it("produces exactly the golden bytes", () => {
    expect(canonicalJson(JSON.parse(source) as object)).toBe(golden);
  });

  it("is a fixed point: canonicalizing the golden reproduces it", () => {
    expect(canonicalJson(JSON.parse(golden) as object)).toBe(golden);
  });

  /*
   * Independent of the implementation: nothing is dropped, added or altered by
   * canonicalization, only reordered. Compared order-insensitively so the
   * sorting under test cannot satisfy the assertion by itself.
   */
  it("loses nothing -- the golden holds exactly the source's data", () => {
    expect(deepEqual(JSON.parse(golden), JSON.parse(source))).toBe(true);
  });

  it("sorts keys at every depth of a seven-level document", () => {
    expect(keysSortedEverywhere(JSON.parse(golden))).toBe(true);
    // The fixture is not accidentally pre-sorted, or the check above proves nothing.
    expect(keysSortedEverywhere(JSON.parse(source))).toBe(false);
  });

  it("ends with a single trailing newline and no other trailing whitespace", () => {
    expect(golden.endsWith("}\n")).toBe(true);
    expect(golden).not.toMatch(/[ \t]\n/);
  });

  /*
   * The independent oracle. Sorting is reimplemented here, deliberately not
   * shared with the code under test, and the expected bytes come from
   * JSON.stringify -- a different implementation entirely. If canonicalJson's
   * formatting ever diverges from "sorted, two-space, trailing newline", this
   * fails without any golden file being involved.
   */
  it("agrees byte for byte with an independently sorted JSON.stringify", () => {
    const sortedDeep = (value: unknown): unknown => {
      if (Array.isArray(value)) return value.map(sortedDeep);
      if (value && typeof value === "object") {
        return Object.fromEntries(
          Object.keys(value).sort().map((key) => [key, sortedDeep((value as Record<string, unknown>)[key])]),
        );
      }
      return value;
    };

    const document = JSON.parse(source) as object;
    const expected = `${JSON.stringify(sortedDeep(document), null, 2)}\n`;
    expect(canonicalJson(document)).toBe(expected);
  });

  it("holds for an already-ordered document too, where sorting changes nothing", () => {
    const alreadyOrdered = JSON.parse(golden) as object;
    expect(canonicalJson(alreadyOrdered)).toBe(`${JSON.stringify(alreadyOrdered, null, 2)}\n`);
  });
});
